development:
  adapter: postgresql
  encoding: utf8
  database: highlander_agile_aus_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: highlander_agile_aus_test
  pool: 5
  host: localhost
