development:
  adapter: postgresql
  encoding: utf8
  database: highlander_development
  pool: 5
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: highlander_test
  pool: 5
  host: localhost